project:
  type: website
  output-dir: docs

website:
  title: "How to derive the bell curve"
  bread-crumbs: true
  page-navigation: true
  navbar:
    left:
      - text: Day 1
        href: day1.qmd
      - text: Day 2
        href: day2.qmd
      - text: Day 3
        href: day3.qmd
      - text: Day 4
        href: day4.qmd
      - text: Day 4'
        href: day4 copy.qmd
      - text: Day 5
        href: day5.qmd
    right:
      - icon: github
        href: https://github.com/apurvanakade/
        aria-label: GitHub
  open-graph: true
  site-url: https://apurvanakade.github.io/
  repo-url: https://github.com/apurvanakade/2026-Summer-Mathcamp-LeastSquares
  search:
    type: overlay
    location: navbar
  
execute:
  # Ensure Quarto preview uses the same Python/Jupyter environment.
  python: /Users/apurvanakade/miniconda3/bin/python
  echo: false
  cache: true

format:
  html:
    theme:
      light: cosmo
      dark: cyborg
    html-math-method: katex
    page-layout: full
  pdf:
    keep-tex: true
# output-dir: docs