project:
  type: website
  output-dir: docs

website:
  title: "How to derive the bell curve"
  bread-crumbs: true
  page-navigation: true
  navbar:
    right:
      - icon: github
        href: https://github.com/apurvanakade/
        aria-label: GitHub
  sidebar: 
    style: floating
    search: true
    contents: 
      - day1.qmd
      - day2.qmd
  open-graph: true
  site-url: https://apurvanakade.github.io/
  repo-url: https://github.com/apurvanakade/2026-Summer-Mathcamp-LeastSquares
  search:
    type: overlay
    location: navbar
  
execute:
  # Ensure Quarto preview uses the same Python/Jupyter environment.
  python: /Users/apurvanakade/miniconda3/bin/python
  echo: false
  cache: true

format:
  html:
    theme:
      light: cosmo
      dark: cyborg
    html-math-method: katex
  pdf:
    keep-tex: true
# output-dir: docs